apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Service URLs
  MENU_SERVICE_URL: "http://menu:5002/menu"
  DRIVER_SERVICE_URL: "http://driver:5001/driver"
  BOOKING_SERVICE_URL: "http://booking:5003/booking"
  CONFIRM_SERVICE_URL: "http://confirm:5004/confirm"

  # General configs
  ENVIRONMENT: "development"
  API_VERSION: "v1"
