name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Python testing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests

    - name: Run tests and build images
      run: |
        SERVICES=("admin" "booking" "confirm" "driver" "menu")
        for SERVICE in "${SERVICES[@]}"; do
          echo "🔍 Testing $SERVICE"
          if [ -f "$SERVICE/tests/test_main.py" ]; then
            PYTHONPATH=$SERVICE pytest $SERVICE/tests --maxfail=1 --disable-warnings -v
          else
            echo "⚠️ No tests found for $SERVICE"
          fi

          echo "🐳 Building Docker image for $SERVICE"
          docker build -t $SERVICE:latest ./$SERVICE
        done
